baseURL = ""
languageCode = "en-us"
title = "Rocky Linux"

[params]
description = "Rocky Linux is an open enterprise Operating System designed to be 100% bug-for-bug compatible with Enterprise Linux."
images = ["img/cover.png"]

[params.logo]
url = "img/logo.png"
width = 127
height = 40

[params.image]
url = "img/cover.png"
width = 800
height = 600
